name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build the project
    runs-on: ubuntu-latest
    strategy:
      matrix:
        projects:
          [
            "Analog to Digital Conversion",
            "LCD Display",
            "PWM",
            "Serial Communication (USART)",
            "Seven Segment Display",
            "Stepper Motor",
            "Timer",
          ]
    steps:
      - name: Download the source code
        uses: actions/checkout@v1
      - name: Build
        uses: atick-faisal/mplabx-xc8-build-action@v1.0.0
        with:
          project: ${{ matrix.projects }}
          configuration: default
